#! /bin/sh
#
# gesl -- This shell script starts and stops the gesture listener daemon.
#
# chkconfig: 345 90 20
# description: gesl is the gesture listener daemon
# processname: gesl

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=gesl

[ -f /etc/default/rcS ] && . /etc/default/rcS

case "$1" in
    start)
        echo -n "Starting gesl daemon: "
        start-stop-daemon --start --pidfile /var/run/${NAME}.pid --make-pidfile --background -x /usr/bin/${NAME}
        if [ $? = 0 ]; then
            echo "(ok)"
        else
            echo "(failed)"
        fi
        ;;
    stop)
        echo -n "Stopping gesl daemon: "
        start-stop-daemon --stop --pidfile /var/run/${NAME}.pid --oknodo
        rm -f /var/run/${NAME}.pid
        echo "(done)"
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/gesl {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
